### ISSUE TITLE
Set the message key in Kafka topics

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#159]
**## Problem Statement**
Currently message key in Kafka is not set by the Source connector

**## Proposed Solution**
Use **ExtractField** & **ValueToKey** SMT to set the message key to the value of the _id_ field from the Cosmos DB document

**## Acceptance Criteria**

- [ ] If the approach in the comments works: An integration test and/or walkthrough/tutorial document using SMT to achieve this functionality showing the correct set of configurations.
- [ ] If the approach does not work: Create a new work item with findings and information.

**## Additional Context**
Refer to comments in the discussion for usage and examples of using **ExtractField** and **ValueToKey**

**Comment by ryancrawcour** [comment]
need to investigate whether Single Message Transforms utilizing the **ValueToKey** SMT could be configured to extract data from the _Value_ and use that to set the _Key_.

ValueToKey | Create or replace record key with data from record value. | Useful when a source connector does not populate the record key but only the value with a Struct. | fields – list of field names to hoist into the record key as a primitive (single field ) / Struct (multiple fields)force.struct – force wrapping in a Struct even when it is a single field
-- | -- | -- | --

**Comment by ryancrawcour** [comment]
[ExtractField SMT](https://docs.confluent.io/platform/current/connect/transforms/extractfield.html)

```
"transforms": "ExtractField",
"transforms.extractField.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
"transforms.extractField.field":"id"
```

Before: {"id": 42, "cost": 4000}

After: 42

**Comment by sivamu** [comment]
Trying out both of the transforms but am running into the following exception:
```
Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:196)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:122)
        at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:50)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:339)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:264)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.connect.errors.DataException: Only Map objects supported in absence of schema for [copying fields from value to key], found: java.lang.String
        at org.apache.kafka.connect.transforms.util.Requirements.requireMap(Requirements.java:38)
        at org.apache.kafka.connect.transforms.ValueToKey.applySchemaless(ValueToKey.java:72)
        at org.apache.kafka.connect.transforms.ValueToKey.apply(ValueToKey.java:65)
        at org.apache.kafka.connect.runtime.TransformationChain.lambda$apply$0(TransformationChain.java:50)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:146)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:180)
        ... 11 more
```

I think this is happening because the source connector is writing the data as a `String` to the Kafka topic. Even if the JSON converter is applied to the source connector, I'm thinking that the SMT is applied _before_ being processed by the converter. I still need to do a bit more investigation into this.

If the SMT expects the messages to be in JSON before hitting the converter, then we would need to create the `SourceRecords` with JSON data rather than `String` as we currently do. I don't think this is possible (also needs a bit more investigation) since creating a JSON based `SourceRecord` requires a pre-populated schema object. I am not sure if CosmosDB provides this or it might be quite complex to get a schema from an existing `JSONNode` object.

**Comment by ryancrawcour** [comment]
the SMT should be applied between our Source Connector and Kafka. i.e. after we've passed the data off to Connect, but before it writes the data to Kafka, but before the converter, correct. 

the order of running is 
kafka -> converter -> transform -> connector -> transform -> converter -> kafka

**Comment by ryancrawcour** [comment]
> we would need to create the SourceRecords with JSON data rather than String as we currently do.

i believe you are correct. we shouldn't be converting the data in the connector. 
unless we're doing conversions to handle data-types. i.e. source system is passing in a type that we can't support in JSON. 
check how other connectors (and the docs i linked to) handle data-type conversion.
