### ISSUE TITLE
Tests fail with Mockito

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#169]
## Description
Tests fail during build with - 

**Mockito cannot mock this class: class com.azure.cosmos.CosmosAsyncClient.**
Can not mock final classes with the following settings :
 - explicit serialization (e.g. withSettings().serializable())
 - extra interfaces (e.g. withSettings().extraInterfaces(...))

You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, interface java.io.Closeable, class com.azure.cosmos.CosmosAsyncClient, interface java.lang.AutoCloseable]
	at com.microsoft.azure.cosmosdb.kafka.connect.source.CosmosDBSourceTaskTest.setup(CosmosDBSourceTaskTest.java:64)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, interface java.io.Closeable, class com.azure.cosmos.CosmosAsyncClient, interface java.lang.AutoCloseable]
	at com.microsoft.azure.cosmosdb.kafka.connect.source.CosmosDBSourceTaskTest.setup(CosmosDBSourceTaskTest.java:64)
Caused by: java.lang.IllegalStateException: 

Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
	at com.microsoft.azure.cosmosdb.kafka.connect.source.CosmosDBSourceTaskTest.setup(CosmosDBSourceTaskTest.java:64)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 59
	at com.microsoft.azure.cosmosdb.kafka.connect.source.CosmosDBSourceTaskTest.setup(CosmosDBSourceTaskTest.java:64)

## Expected Behavior
- All unit tests should succeed

## Reproduce
```mvn clean package``` 

## Additional Context 
issue conversation that first raised this - 
https://github.com/microsoft/kafka-connect-cosmosdb/issues/156#issuecomment-736154464

full error log - 
[mvn_clean_package.txt](https://github.com/microsoft/kafka-connect-cosmosdb/files/5626362/mvn_clean_package.txt)

**Comment by ryancrawcour** [comment]
addresses build error raised in #156

**Comment by ryancrawcour** [comment]
Thus far unable to reproduce this issue. Will try dig in further to see if we can uncover more details.

**Comment by ryancrawcour** [comment]
This appears related to version of Java. 
We should be targeting Java 8 still at this stage. 
And ideally Zulu OpenJDK for Java as per the MSFT docs below

https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-jdk-long-term-support
