### ISSUE TITLE
Resolve SchemaAndValue conversion issue with Array & Arrays of json object

### ISSUE THREAD

**Issue by kev-ms** [microsoft/kafka-connect-cosmosdb#225]

**Comment by kev-ms** [comment]
When JSON object contains Array of any data type or Array of JSON Object, serialization of data fails with below error

`org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type ARRAY: class com.fasterxml.jackson.databind.node.ArrayNode for field: "children"
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:245)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
        at com.microsoft.azure.cosmosdb.kafka.connect.source.JsonToStruct.lambda$recordToSchemaAndValue$0(JsonToStruct.java:39)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at com.microsoft.azure.cosmosdb.kafka.connect.source.JsonToStruct.recordToSchemaAndValue(JsonToStruct.java:34)`

**Comment by kev-ms** [comment]
`org.apache.kafka.connect.errors.DataException: Struct schemas do not match.
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:252)
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:258)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
        at com.microsoft.azure.cosmosdb.kafka.connect.source.JsonToStruct.lambda$recordToSchemaAndValue$0(JsonToStruct.java:42)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at com.microsoft.azure.cosmosdb.kafka.connect.source.JsonToStruct.recordToSchemaAndValue(JsonToStruct.java:37)
        at com.microsoft.azure.cosmosdb.kafka.connect.source.CosmosDBSourceTask.fillRecords(CosmosDBSourceTask.java:119)
        at com.microsoft.azure.cosmosdb.kafka.connect.source.CosmosDBSourceTask.poll(CosmosDBSourceTask.java:90)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)`
