### ISSUE TITLE
INT64 field terminates CosmosDB source connector task while moving data into Kafka

### ISSUE THREAD

**Issue by bluedog13** [microsoft/kafka-connect-cosmosdb#418]
## Description

I have records in CosmosDB with the following property
```
{
    .........................
    "createOnUnixMs": 1637258355246,
     .........................
}
```

I am using the source connector to move the data into a Kafka topic using the following
```
{

     "name": "cosmosdb-source-connector",
      "config": {
                  .........................
                 "key.converter"  : "org.apache.kafka.connect.json.JsonConverter",
                 "key.converter.schemas.enable"  : "false",
                 "value.converter"   : "org.apache.kafka.connect.json.JsonConverter",
                 "value.converter.schemas.enable"   : "false",
                   .........................
     }
}
```

I run into the below error and the connector task fails/terminates. 
```
ERROR WorkerSourceTask{id=cosmosdb-source-connector-1} **Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
connect    | org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "createOnUnixMs",** schema type: INT64
connect    | 	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:220)
connect    | 	at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
connect    | 	at com.azure.cosmos.kafka.connect.source.JsonToStruct.lambda$recordToSchemaAndValue$0(JsonToStruct.java:39)
connect    | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
connect    | 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
connect    | 	at com.azure.cosmos.kafka.connect.source.JsonToStruct.recordToSchemaAndValue(JsonToStruct.java:35)
connect    | 	at com.azure.cosmos.kafka.connect.source.CosmosDBSourceTask.fillRecords(CosmosDBSourceTask.java:186)
connect    | 	at com.azure.cosmos.kafka.connect.source.CosmosDBSourceTask.poll(CosmosDBSourceTask.java:149)
connect    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:291)
connect    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248)
connect    | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
connect    | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:241)
connect    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect    | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Expected Behavior

- I was hoping the connector would copy the document from CosmosDB to Kafka topic because clearly the value is not null, as being mentioned in the error stack (above)

## Additional Context

Surprisingly,  the sink connector works just fine when moving the record containing the above field (createOnUnixMs) to CosmosDB.

**Comment by ryancrawcour** [comment]
does every record in Cosmos DB have this field, or are there some records where this field is undefined, or null?

**Comment by ryancrawcour** [comment]
thanks for the additional info. there must be something weird that is happening with that datatype. will need to investigate.

**Comment by robcam73** [comment]
Is their likely to be a fix for this? I am also running into this issue

**Comment by robcam73** [comment]
I have a fix for this issue, but I do not know how to go about submitting. 

Please add

else if (nodeValue.isLong()) {
                value = nodeValue.longValue();
            }

to line 173 of package com.azure.cosmos.kafka.connect.source.JsonToStruct

Currently, it is not parsing long values

**Comment by ryancrawcour** [comment]
Thanks for looking in to this.
You can fork the repo, apply the fix, add a test, and submit a PR back to this repo.

Else I'll look in to it tomorrow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robcam73** [comment]
I have created a pull request for the fix

Thanks
