### ISSUE TITLE
Sink bug when when using AvroConverter -> Error: Argument 'recordValue' is not valid map format.

### ISSUE THREAD

**Issue by flopetegui** [microsoft/kafka-connect-cosmosdb#493]
## Description

WorkerSinkTask fails to write message to cosmosdb citing that record value is not in a valid 'map' format.
Sink connector is pulling from kafka topic that uses AVRO serializer and schema registry.

## Expected Behavior

Sink connector should publishes message from topic to cosmos db container.

## Reproduce

Here is the Avro schema from .avsc file.

    {
      "type": "record",
      "name": "CompanyResponse",
      "namespace": "com.company.ns",
      "fields": [
        {
          "name": "companyId",
          "type": {
            "type": "string",
            "avro.java.string": "String"
          }
        },
        {
          "name": "companyName",
          "type": [
            "null",
            {
              "type": "string",
              "avro.java.string": "String"
            }
          ],
          "default": null
        }
      ],
      "connect.name": "com.company.ns.CompanyResponse"
    }

The Java code snippet that produces the message to 'company-response-topic' topic

    Schema.Parser parser = new Schema.Parser();
    Schema schema = parser.parse(CompanyResponse.SCHEMA$.toString());
    GenericRecord avroRecord = new GenericData.Record(schema);
    
    avroRecord.put("companyId", "JS9DJ354GSN8");
    avroRecord.put("companyName", "My Company");
    
    ProducerRecord<Object, Object> record = new ProducerRecord<>("company-response-topic", "JS9DJ354GSN8", avroRecord);
    kafkaProducer.send(record);

The Cosmos sink configuration

    {
      "name": "cosmosdb-sink-connector",
      "config": {
        "connector.class": "com.azure.cosmos.kafka.connect.sink.CosmosDBSinkConnector",
        "tasks.max": "1",
        "topics": [
          "company-response-topic"
        ],
        "value.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter.schemas.enable": "true",
        "value.converter.schema.registry.url": "http://sregistry:8081",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "key.converter.schemas.enable": "false",
        "connect.cosmos.connection.endpoint": "https://my-cosmos-instance.azure.com:443/",
        "connect.cosmos.master.key": "<my key>",
        "connect.cosmos.databasename": "database",
        "connect.cosmos.containers.topicmap": "company-response-topic#company-response-topic",
        "connect.cosmos.connection.gateway.enabled": "true",
        "id.strategy": "com.azure.cosmos.kafka.connect.sink.id.strategy.FullKeyStrategy"
      }
    }

Cosmos db configurations includes a partition key '/companyId'

Here are logs indicating the error from WorkerSinkTask 

    [2022-10-25 01:35:32,128] INFO Sending 1 records to be written (com.azure.cosmos.kafka.connect.sink.CosmosDBSinkTask)
    [2022-10-25 01:35:32,226] ERROR WorkerSinkTask{id=cosmosdb-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Argument 'recordValue' is not valid map format. (org.apache.kafka.connect.runtime.WorkerSinkTask)
    java.lang.IllegalArgumentException: Argument 'recordValue' is not valid map format.
            at com.azure.cosmos.implementation.guava25.base.Preconditions.checkArgument(Preconditions.java:136)
            at com.azure.cosmos.kafka.connect.sink.BulkWriter.getPartitionKeyValue(BulkWriter.java:103)
            at com.azure.cosmos.kafka.connect.sink.BulkWriter.writeCore(BulkWriter.java:62)
            at com.azure.cosmos.kafka.connect.sink.SinkWriterBase.write(SinkWriterBase.java:26)
            at com.azure.cosmos.kafka.connect.sink.CosmosDBSinkTask.put(CosmosDBSinkTask.java:123)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:584)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
            at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
            at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:200)
            at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:255)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:829)

Logs aknowledge that a record needs to be written,  but then fails at **_BulkWriter.getPartitionKeyValue(BulkWriter.java:103)_** where it fails the precondition
**_checkArgument(recordValue instanceof Map, "Argument 'recordValue' is not valid map format.");_**

## Additional Context

If I use json instead of Avro, the sink works. This seems like an avro specific issue.

**Comment by kushagraThapar** [comment]
@flopetegui thanks for reporting this, and adding the required details. Wondering if you can provide more information related to the version of sink connector being used. 
Also, we recently added support for bulk in the sink connector. Can you please repro this on a version prior to bulk support. That way we can isolate the issue if it is related to the recent addition of bulk support or if the issue has always been there.

**Comment by xinlian12** [comment]
@flopetegui please disable the bulk mode and see whether the issue still repros -> connect.cosmos.sink.bulk.enabled=false

**Comment by flopetegui** [comment]
I am using v1.6.0 of the plugin downloaded from Confluent hub.

@xinlian12 added the property as you instructed. Still failed, but with a different message.


        [2022-10-26 00:32:51,697] INFO Sending 1 records to be written (com.azure.cosmos.kafka.connect.sink.CosmosDBSinkTask)
        [2022-10-26 00:32:51,707] ERROR locationEndpoint is null because ClientRetryPolicy::onBeforeRequest(.) is not invoked, probably request creation failed due to invalid options, serialization setting, etc. (com.azure.cosmos.implementation.ClientRetryPolicy)
        [2022-10-26 00:32:51,707] ERROR onBeforeSendRequest is not invoked, encountered failure due to request being null (com.azure.cosmos.implementation.RenameCollectionAwareClientRetryPolicy)
        java.lang.IllegalArgumentException: Failed to serialize the object into json
                at com.azure.cosmos.implementation.Utils.serializeJsonToByteBuffer(Utils.java:699)
                at com.azure.cosmos.implementation.InternalObjectNode.serializeJsonToByteBuffer(InternalObjectNode.java:116)
                at com.azure.cosmos.BridgeInternal.serializeJsonToByteBuffer(BridgeInternal.java:110)
                at com.azure.cosmos.implementation.RxDocumentClientImpl.getCreateDocumentRequest(RxDocumentClientImpl.java:1470)
                at com.azure.cosmos.implementation.RxDocumentClientImpl.upsertDocumentInternal(RxDocumentClientImpl.java:1837)
                at com.azure.cosmos.implementation.RxDocumentClientImpl.lambda$upsertDocument$39(RxDocumentClientImpl.java:1829)
                at com.azure.cosmos.implementation.ObservableHelper.lambda$inlineIfPossibleAsObs$1(ObservableHelper.java:44)
                at com.azure.cosmos.implementation.BackoffRetryUtility.lambda$executeRetry$0(BackoffRetryUtility.java:36)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
                at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
                at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
                at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
                at reactor.core.publisher.Mono.block(Mono.java:1706)
                at com.azure.cosmos.CosmosContainer.blockItemResponse(CosmosContainer.java:242)
                at com.azure.cosmos.CosmosContainer.upsertItem(CosmosContainer.java:206)
                at com.azure.cosmos.kafka.connect.sink.PointWriter.writeCore(PointWriter.java:31)
                at com.azure.cosmos.kafka.connect.sink.SinkWriterBase.write(SinkWriterBase.java:26)
                at com.azure.cosmos.kafka.connect.sink.CosmosDBSinkTask.put(CosmosDBSinkTask.java:123)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:584)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:334)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:235)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:204)
                at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:200)
                at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:255)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.lang.Thread.run(Thread.java:829)
        Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.apache.kafka.connect.data.Struct and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
                at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
                at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
                at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
                at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46)
                at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29)
                at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
                at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
                at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
                at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3780)
                at com.azure.cosmos.implementation.Utils.serializeJsonToByteBuffer(Utils.java:695)
                ... 30 more

**Comment by flopetegui** [comment]
The error indicates a potential issue with the ObjectMapper in connector? 
Specifically the conversion of an Avro message to Json structure used to store item in NoSql.

The Avro message is in JSON format, but it includes the type in output.

For example, schema

        {
          "type" : "record",
          "name" : "User",
          "namespace" : "io.confluent.developer.avro",
          "fields" : [ {
            "name" : "name",
            "type" : "string"
          }, {
            "name" : "favorite_number",
            "type" : [ "null", "int" ],
            "default" : null
          }, {
            "name" : "favorite_color",
            "type" : [ "null", "string" ],
            "default" : null
          } ]
        }



Will results in JSON message,

        {
          "name": "cricket007",
          "favorite_number": {
            "int": 42
          },
          "favorite_color": {
            "string": "green"
          }
        }

**Comment by xinlian12** [comment]
thanks @flopetegui, agree with you, seems mattered to the ObjectMapper used in the SDK, will pick up this issue in the next 2-3 weeks,

**Comment by ilyasdresden** [comment]
Hi, we faced with same issue. Is there any update on this? Thanks.

**Comment by xinlian12** [comment]
@flopetegui / @ilyasdresden due to some other higher priority working items, this issue will likely be picked up sometime in March. 
Is that possible to use JsonConverter instead?

**Comment by ilyasdresden** [comment]
@xinlian12, thank you for the information and an option. Unfortunately, it would not work for us because we are not owning the topic.

**Comment by renebrandnewday** [comment]
Same here. 

We are using Avro.

`
ERROR WorkerSinkTask{id=cosmos-rene-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Failed to serialize the object into json (org.apache.kafka.connect.runtime.WorkerSinkTask:609)
java.lang.IllegalArgumentException: Failed to serialize the object into json
	at com.azure.cosmos.implementation.Utils.serializeJsonToByteBuffer(Utils.java:699)
	at com.azure.cosmos.implementation.InternalObjectNode.serializeJsonToByteBuffer(InternalObjectNode.java:116)
	at com.azure.cosmos.BridgeInternal.serializeJsonToByteBuffer(BridgeInternal.java:110)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.getCreateDocumentRequest(RxDocumentClientImpl.java:1470)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.upsertDocumentInternal(RxDocumentClientImpl.java:1837)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.lambda$upsertDocument$39(RxDocumentClientImpl.java:1829)
	at com.azure.cosmos.implementation.ObservableHelper.lambda$inlineIfPossibleAsObs$1(ObservableHelper.java:44)
	at com.azure.cosmos.implementation.BackoffRetryUtility.lambda$executeRetry$0(BackoffRetryUtility.java:36)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77)
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.azure.cosmos.CosmosContainer.blockItemResponse(CosmosContainer.java:242)
	at com.azure.cosmos.CosmosContainer.upsertItem(CosmosContainer.java:206)
	at com.azure.cosmos.kafka.connect.sink.PointWriter.writeCore(PointWriter.java:31)
	at com.azure.cosmos.kafka.connect.sink.SinkWriterBase.write(SinkWriterBase.java:26)
	at com.azure.cosmos.kafka.connect.sink.CosmosDBSinkTask.put(CosmosDBSinkTask.java:123)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1707)
		... 16 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.apache.kafka.connect.data.Struct and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3780)
	at com.azure.cosmos.implementation.Utils.serializeJsonToByteBuffer(Utils.java:695)
	... 30 more
`

**Comment by Nardu92** [comment]
I had the same issue both with the CosmosDb sink 1.6.0 and 1.3.1 with base image confluentinc/cp-kafka-connect-base:7.3.2
But I found a workaround: by downgrading the Connector base image to confluentinc/cp-kafka-connect-base:6.1.7 it works.

**Comment by maoljaca** [comment]
Hey i have the same issue and i checked the code (version 1.7.0). The issue relies due to the followings lines (hopefully):

CosmosDBSinkTask Line 110 - 119

`
                Object recordValue;
                if (record.value() instanceof Struct) {
                    recordValue = StructToJsonMap.toJsonMap((Struct) record.value());
                } else {
                    recordValue = record.value();
                }

                maybeInsertId(recordValue, record);
                toBeWrittenRecordList.add(record);
`

Kafka Connect uses Struct as internal DataStore to store Kafka Messages. It does not directly use Avro format. In this step the Struct should be transformed to Map<String, Object>. This happens but the result is not being added to the "toBeWrittenRecordList".  The values in the Lsit are still structs and that cashes later. 

Thats at least my impression here. Hopefully it helps.

**Comment by kushagraThapar** [comment]
@maoljaca thanks for the suggestion, I have tried fixing this bug in the below PR - would appreciate if you can take a look (just in case I missed anything), thanks - https://github.com/microsoft/kafka-connect-cosmosdb/pull/503

**Comment by maoljaca** [comment]
@kushagraThapar i will test the version asap. Thanks for your PR!

**Comment by maoljaca** [comment]
About my currentissue with the nested avro i have the following idea (tried to open discussion but didn't work due to permisison i think):

Currently https://github.com/microsoft/kafka-connect-cosmosdb/blob/v1.7.1/src/main/java/com/azure/cosmos/kafka/connect/sink/StructToJsonMap.java handles transformation of Struct to a nested Map of List and Maps.

The recursion seems fine, but complexer Object still crash (we have an issue currently with large nested object). Some nested struct is not properly resolved.

We currently use a workaround where we use  a Converter to convert Avro to Plain JSON and write that straight to Cosmos DB via Sink Connector. The Converter is available and can transform Struct to plain JSON. This could be written to Cosmos DB. 

Benefits:

- Less code
- Converter is well tested for many use cases
- Would resolve the current bug for heavily nested objects

Draw backs:
- Certain data types not well supported in plain json (for example Dates)
- Feels a bit hacky though since Converter jobs were to convert Data from Kafka Topics or write to Kafka Topics.

Here a Code Snippet:
`import org.apache.kafka.connect.data.Schema;
import org.apache.kafka.connect.data.SchemaBuilder;
import org.apache.kafka.connect.data.Struct;
import org.apache.kafka.connect.json.JsonConverter;
import org.junit.Test;

import java.nio.charset.StandardCharsets;
import java.util.Collections;

public class TestStruct {

    @Test
    public void testStruct() {

        Schema schema = SchemaBuilder.struct()
                .field("make", Schema.STRING_SCHEMA)
                .field("model", Schema.STRING_SCHEMA)
                .field("year", Schema.INT32_SCHEMA)
                .field("color", Schema.STRING_SCHEMA)
                .field("userBefore", SchemaBuilder.struct()
                        .field("id", Schema.INT32_SCHEMA)
                        .field("name", Schema.STRING_SCHEMA)
                        .field("email", Schema.STRING_SCHEMA)
                        .build())
                .build();

// Create a Struct object representing car data
        Struct carData = new Struct(schema)
                .put("make", "Toyota")
                .put("model", "Camry")
                .put("year", 2022)
                .put("userBefore", new Struct(schema.field("userBefore").schema())
                        .put("id", 1)
                        .put("name", "John Doe")
                        .put("email", "john.doe@gmail.com"))
                .put("color", "red");

// Create a JsonConverter object
        JsonConverter jsonConverter = new JsonConverter();
        jsonConverter.configure(Collections.singletonMap("schemas.enable", false), false);

// Convert the car data Struct object to JSON
        byte[] payload = jsonConverter.fromConnectData("car-data-topic", schema, carData);
        String json = new String(payload, StandardCharsets.UTF_8);

        System.out.println(json);`

Output is:

`{
  "make": "Toyota",
  "model": "Camry",
  "year": 2022,
  "color": "red",
  "userBefore": {
    "id": 1,
    "name": "John Doe",
    "email": "john.doe@gmail.com"
  }
}`




What do you think about it?

Best Marko

**Comment by maoljaca** [comment]
i'll create a new one. I try to give a solution as well to it.

**Comment by kushagraThapar** [comment]
@maoljaca appreciate it, thank you!
