### ISSUE TITLE
cosmos.id.strategy value is different than configured

### ISSUE THREAD

**Issue by esquare666** [microsoft/kafka-connect-cosmosdb#569]
## Description

- cosmos.id.strategy configured as FullKeyStrategy, however logs shows that "ProvidedInValueStrategy"

## Expected Behavior

I have configured sink connect (**version: 1.15.0**) and configured connector as "cosmos.id.strategy": "**FullKeyStrategy**" however in logs, shows that "**ProvidedInValueStrategy**" , this is not matching with what I have configured
CosmosDBSinkConfig values: 
	connect.cosmos.connection.endpoint = https://xxxxxx.documents.azure.com:443/
	connect.cosmos.connection.gateway.enabled = false
	connect.cosmos.connection.sharing.enabled = false
	connect.cosmos.containers.topicmap = dev.test-topic#test-container
	connect.cosmos.databasename = cosmosdb01
	connect.cosmos.master.key = [hidden]
	connect.cosmos.provider.name = null
	connect.cosmos.sink.bulk.compression.enabled = true
	connect.cosmos.sink.bulk.enabled = true
	connect.cosmos.sink.maxRetryCount = 10
	errors.tolerance = none
	**id.strategy = class com.azure.cosmos.kafka.connect.sink.id.strategy.ProvidedInValueStrategy**
 (com.azure.cosmos.kafka.connect.sink.CosmosDBSinkConfig:370)

Can someone clarify whether the config is correct 
"cosmos.id.strategy": "**FullKeyStrategy**" 

and we are getting an error:
 ProvidedInConfig values: 
	jsonPath = $.id
 (com.azure.cosmos.kafka.connect.sink.id.strategy.ProvidedInConfig:370)

Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Could not evaluate JsonPath $.id (org.apache.kafka.connect.runtime.WorkerSinkTask:632)
org.apache.kafka.connect.errors.ConnectException: Could not evaluate JsonPath $.id
	at com.azure.cosmos.kafka.connect.sink.id.strategy.ProvidedInStrategy.generateId(ProvidedInStrategy.java:35)
	at com.azure.cosmos.kafka.connect.sink.id.strategy.ProvidedInValueStrategy.generateId(ProvidedInValueStrategy.java:3)
	at com.azure.cosmos.kafka.connect.sink.CosmosDBSinkTask.maybeInsertId(CosmosDBSinkTask.java:202)
	at com.azure.cosmos.kafka.connect.sink.CosmosDBSinkTask.put(CosmosDBSinkTask.java:126)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:599)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:346)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:243)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:212)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:229)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:284)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.jayway.jsonpath.PathNotFoundException: No results for path: $['id']
[2024-05-03 01:04:26,530] ERROR [cosmosdb-sink-connector|task-0] WorkerSinkTask{id=cosmosdb-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:237)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:634)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:346)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:243)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:212)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:229)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:284)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.ConnectException: Could not evaluate JsonPath $.id
	at com.azure.cosmos.kafka.connect.sink.id.strategy.ProvidedInStrategy.generateId(ProvidedInStrategy.java:35)
	at com.azure.cosmos.kafka.connect.sink.id.strategy.ProvidedInValueStrategy.generateId(ProvidedInValueStrategy.java:3)
	at com.azure.cosmos.kafka.connect.sink.CosmosDBSinkTask.maybeInsertId(CosmosDBSinkTask.java:202)
	at com.azure.cosmos.kafka.connect.sink.CosmosDBSinkTask.put(CosmosDBSinkTask.java:126)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:599)
	... 11 more
Caused by: com.jayway.jsonpath.PathNotFoundException: No results for path: $['id']

**Comment by kushagraThapar** [comment]
@xinlian12 can you please take a look at this issue? We should also check if its a problem in our new connector as well?

**Comment by xinlian12** [comment]
@esquare666 the config name should be id.strategy. Can you try:
"id.strategy": "com.azure.cosmos.kafka.connect.sink.id.strategy.FullKeyStrategy"

**Comment by esquare666** [comment]
Thank you. it worked with full class name
	**id.strategy = class com.azure.cosmos.kafka.connect.sink.id.strategy.FullKeyStrategy**

Is that possible to use without full class name? would be much appreciated If you could do in future release. Also, not sure whether I can able to find in the documentation. In couple of documents mentioned cosmos.id.strategy instead of id.strategy.
